apiVersion: v1
kind: Secret
metadata:
  name: mongodb-uri
  namespace: {{ .Release.Namespace }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  username: {{ .Values.env.secrets.username }}
  password: {{ .Values.env.secrets.password }}
  port: {{ .Values.env.secrets.port }}
  host: {{ .Values.env.secrets.host }}
