apiVersion: v1
kind: Pod
metadata:
  name: build-pod
spec:
  containers:
  - name: ez-docker-helm-build
    image: ezezeasy/ez-docker-helm-build:1.41
    command:
      - cat
    tty: true
    volumeMounts:
      - mountPath: /home/jenkins/agent
        name: workspace-volume
        readOnly: false
    # Add kubectl installation here
    initContainers:
    - name: install-kubectl
      image: alpine:3.18
      command: ['sh', '-c', 'apk add --no-cache curl && curl -LO "https://dl.k8s.io/release/v1.28.0/bin/linux/amd64/kubectl" && chmod +x ./kubectl && mv ./kubectl /usr/local/bin/kubectl']
      volumeMounts:
      - name: workspace-volume
        mountPath: /usr/local/bin
  volumes:
  - name: workspace-volume
    emptyDir: {}
